---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: 'balance-transfer'

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: 'hlfv1'

#
# Describe what the target network is/does.
#
description: 'Balance Transfer Network'

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: '1.0'

#
# The client section will be added on a per org basis see org1.yaml and partyb.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  irs:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      partya.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      partyb.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - irscc:v0

#
# list of participating organizations in this network
#
organizations:
  partya:
    mspid: partya
    peers:
      - partya.example.com
    # certificateAuthorities:
    # - ca-partya
    # adminPrivateKey:
    #   path: /cryptogen/crypto-config/peerOrganizations/partya.example.com/users/Admin@partya.example.com/msp/keystore/5f67d2d51772389c12ddd664d01d82f70733438e9e97a0b3b29a48d09cd86f24_sk
    # signedCert:
    #   path: /cryptogen/crypto-config/peerOrganizations/partya.example.com/users/Admin@partya.example.com/msp/signcerts/Admin@partyb.example.com-cert.pem

  partyb:
    mspid: partyb
    peers:
      - partyb.example.com
    # certificateAuthorities:
    # - ca-partyb
    # adminPrivateKey:
    #   path: /cryptogen/crypto-config/peerOrganizations/partyb.example.com/users/Admin@partyb.example.com/msp/keystore/5f67d2d51772389c12ddd664d01d82f70733438e9e97a0b3b29a48d09cd86f24_sk
    # signedCert:
    #   path: /cryptogen/crypto-config/peerOrganizations/partyb.example.com/users/Admin@partyb.example.com/msp/signcerts/Admin@partyb.example.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.example.com:
    url: grpc://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.example.com

    # tlsCACerts:
    #   path: /cryptogen/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  partya.example.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: partya.example.com
    # tlsCACerts:
    #   path: /cryptogen/crypto-config/peerOrganizations/partya.example.com/peers/partya.example.com/tls/ca.crt

  partyb.example.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: partyb.example.com
    # tlsCACerts:
    #   path: /cryptogen/crypto-config/peerOrganizations/partyb.example.com/peers/partyb.example.com/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-partya:
    url: http://ca-partya:7054
    httpOptions:
      verify: false
    # tlsCACerts:
    #   path: /cryptogen/crypto-config/peerOrganizations/partya.example.com/ca/ca.partya.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-partya

  ca-partyb:
    url: http://ca-partyb:7054
    httpOptions:
      verify: false
    # tlsCACerts:
    #   path: /cryptogen/crypto-config/peerOrganizations/partyb.example.com/ca/ca.partyb.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-partyb
